name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [self-hosted, windows, x64] 
    steps:
      - uses: actions/checkout@v3

      - name: Teste unit project
        run: .\build.bat src\application CursoGitHubActions.dproj
